# Generated by Django 2.2.6 on 2020-05-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0003_auto_20200531_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='relation_with_item',
            field=models.ManyToManyField(through='dataprocessing.Relation', to='dataprocessing.Items', verbose_name='Связи айтима'),
        ),
    ]
