# Generated by Django 2.2.6 on 2020-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0006_auto_20200601_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(blank=True, max_length=900, verbose_name='Название'),
        ),
    ]
