# Generated by Django 2.2.6 on 2020-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0007_auto_20200902_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rpd_developer',
            field=models.BooleanField(default=False),
        ),
    ]
