#FROM nikolaik/python-nodejs:python3.8-nodejs12
FROM python:3.8

#ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
RUN mkdir /application
WORKDIR /application
COPY . /application
RUN pip install -r requirements.txt