FROM node:16.10.0-alpine as build

WORKDIR /frontend

ENV PATH /frontend/node_modules/.bin:$PATH

COPY . /frontend

RUN npm ci --silent
RUN npm install react-app-rewired -g --silent
RUN npm run build

CMD ["npm", "start"]

