FROM node:13.12.0-alpine as build

WORKDIR /frontend

ENV PATH /frontend/node_modules/.bin:$PATH

COPY . /frontend

RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm run build

CMD ["npm", "start"]

