fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-ast
      - id: debug-statements
      - id: check-added-large-files
        args: [ "--maxkb=1024" ]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/ambv/black
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3
        entry: black
        require_serial: true
        types: [ python ]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        name: ruff
        stages: [ commit ]
        types: [ file, python ]
        args: [ "--fix" ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [ "--py311-plus" ]
