services:
  db:
    env_file:
      - ./application/.env
    container_name: analytics_db_prod
    image: postgres
    ports:
      - "6435:5432"
    volumes:
      - ./dbs/postgres-data-prod:/var/lib/postgresql

  backend:
    env_file:
      - ./application/.env
    container_name: analytics_backend_prod
    build:
      context: ./application
      dockerfile: Dockerfile-prod
    volumes:
      - ./application:/application
    restart: always
    links:
      - db

  nginx:
    image: nginx:latest
    container_name: analytics_nginx_prod
    ports:
      - "80:80"
    volumes:
      - ./application/media:/backend/src/media
      - ./application/static-backend:/backend/src/static-backend
      - ./frontend/build:/frontend/src
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend

volumes:
  postgres_data:
