# Generated by Django 2.2.6 on 2020-04-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationtool',
            name='check_point',
            field=models.BooleanField(blank=True, null=True, verbose_name='Контрольная точка'),
        ),
        migrations.AddField(
            model_name='evaluationtool',
            name='deadline',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок сдачи в неделях'),
        ),
        migrations.AddField(
            model_name='evaluationtool',
            name='max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное значение'),
        ),
        migrations.AddField(
            model_name='evaluationtool',
            name='min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное значение'),
        ),
        migrations.AddField(
            model_name='topic',
            name='online_course',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Реализация раздела дисциплины с помощью онлайн-курса'),
        ),
        migrations.AlterField(
            model_name='disciplinesection',
            name='evaluation_tools',
            field=models.ManyToManyField(blank=True, null=True, to='workprogramsapp.EvaluationTool', verbose_name='Фонды оценочных средств'),
        ),
        migrations.AlterField(
            model_name='disciplinesection',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='evaluationtool',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorworkprogram',
            unique_together=set(),
        ),
    ]
