# Generated by Django 2.2.6 on 2020-04-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0002_auto_20200430_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinesection',
            name='work_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_sections', to='workprogramsapp.WorkProgram', verbose_name='Рабочая программа'),
        ),
    ]
