# Generated by Django 2.2.6 on 2020-04-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0003_auto_20200430_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinesection',
            name='SRO',
            field=models.IntegerField(blank=True, null=True, verbose_name='СРО'),
        ),
        migrations.AddField(
            model_name='disciplinesection',
            name='contact_work',
            field=models.IntegerField(blank=True, null=True, verbose_name='Контактная работа'),
        ),
        migrations.AddField(
            model_name='disciplinesection',
            name='laboratory',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лабораторные занятия'),
        ),
        migrations.AddField(
            model_name='disciplinesection',
            name='lecture_classes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Занятия лекционного типа'),
        ),
        migrations.AddField(
            model_name='disciplinesection',
            name='practical_lessons',
            field=models.IntegerField(blank=True, null=True, verbose_name='Практические занятия'),
        ),
        migrations.AddField(
            model_name='disciplinesection',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего часов'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='discipline_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='workprogramsapp.DisciplineSection', verbose_name='Раздел'),
        ),
    ]
