# Generated by Django 2.2.6 on 2020-05-03 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workprogramsapp', '0004_auto_20200430_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorworkprogram',
            name='competence',
        ),
        migrations.AlterField(
            model_name='disciplinesection',
            name='evaluation_tools',
            field=models.ManyToManyField(blank=True, null=True, related_name='evaluation_tools', to='workprogramsapp.EvaluationTool', verbose_name='Фонды оценочных средств'),
        ),
        migrations.AlterUniqueTogether(
            name='competenceindicator',
            unique_together={('competence', 'indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='routecomposition',
            unique_together={('route', 'user', 'work_program')},
        ),
        migrations.RemoveField(
            model_name='competenceindicator',
            name='field_of_study',
        ),
    ]
