# Generated by Django 2.2.6 on 2020-05-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0005_auto_20200503_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprogram',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='workprogram',
            name='result_goals',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EX', 'Exam'), ('DF', 'Differentiated classification'), ('OS', 'Offset')], max_length=1024)),
                ('semestr', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('deadline', models.IntegerField(blank=True, null=True, verbose_name='Срок сдачи в неделях')),
                ('work_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.WorkProgram')),
            ],
        ),
    ]
