# Generated by Django 2.2.6 on 2020-05-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0006_auto_20200504_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogram',
            name='qualification',
            field=models.CharField(blank=True, choices=[('primary_vocational_education', 'Primary vocational education'), ('secondary_vocational_education', 'Secondary vocational education'), ('bachelor', 'Bachelor'), ('specialist', 'Specialist'), ('master', 'Master')], max_length=1024, null=True, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='work_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_certification', to='workprogramsapp.WorkProgram'),
        ),
    ]
