# Generated by Django 2.2.6 on 2020-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0007_auto_20200504_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogram',
            name='discipline_code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
