# Generated by Django 2.2.6 on 2020-05-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0008_workprogram_discipline_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='educational_profile',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Профиль ОП'),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Название ОП'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='number',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Шифр ОП'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldofstudyworkprogram',
            unique_together={('work_program', 'field_of_study')},
        ),
        migrations.RemoveField(
            model_name='fieldofstudyworkprogram',
            name='competence',
        ),
    ]
