# Generated by Django 2.2.6 on 2020-05-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0008_workprogram_discipline_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='indicators',
        ),
        migrations.AddField(
            model_name='indicator',
            name='competence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.Competences'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompetenceIndicator',
        ),
    ]
