# Generated by Django 2.2.6 on 2020-05-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0009_auto_20200505_1338'),
        ('workprogramsapp', '0009_auto_20200505_1521'),
    ]

    operations = [
    ]
