# Generated by Django 2.2.6 on 2020-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0010_merge_20200505_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinesection',
            name='ordinal_number',
            field=models.IntegerField(default=1, max_length=1024, verbose_name='номер раздела'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicator',
            name='work_programs',
            field=models.ManyToManyField(blank=True, null=True, through='workprogramsapp.IndicatorWorkProgram', to='workprogramsapp.WorkProgram'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='fieldofstudyworkprogram',
        #     unique_together={('work_program', 'field_of_study')},
        # ),
    ]
