# Generated by Django 2.2.6 on 2020-05-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0011_auto_20200506_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinesection',
            options={'ordering': ['ordinal_number']},
        ),
        migrations.AlterUniqueTogether(
            name='fieldofstudyworkprogram',
            unique_together={('work_program', 'field_of_study')},
        ),
    ]
