# Generated by Django 2.2.6 on 2020-05-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0011_auto_20200506_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Описание')),
                ('platform', models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('course_url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='disciplinesection',
            options={'ordering': ['ordinal_number']},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='online_course',
        ),
    ]
