# Generated by Django 2.2.6 on 2020-05-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0012_auto_20200507_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='url_online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_with_online_course', to='workprogramsapp.OnlineCourse', verbose_name='Онлайн курс'),
        ),
    ]
