# Generated by Django 2.2.6 on 2020-05-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0012_auto_20200506_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='faculty',
            field=models.CharField(max_length=150, null=True, verbose_name='Факультет (Структурное подразделение)'),
        ),
    ]
