# Generated by Django 2.2.6 on 2020-05-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0016_auto_20200529_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='number',
            field=models.IntegerField(max_length=1024, verbose_name='номер темы в разделе'),
        ),
    ]
