# Generated by Django 2.2.6 on 2020-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0017_auto_20200531_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographicReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='workprogram',
            name='bibliographic_reference',
            field=models.ManyToManyField(to='workprogramsapp.BibliographicReference', verbose_name='Библиогравическая_ссылка'),
        ),
    ]
