# Generated by Django 2.2.6 on 2020-06-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0020_remove_workprogram_evaluation_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprogram',
            name='bibliographic_reference',
            field=models.ManyToManyField(related_name='bibrefs', to='workprogramsapp.BibliographicReference', verbose_name='Библиогравическая_ссылка'),
        ),
    ]
