# Generated by Django 2.2.6 on 2020-06-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0021_auto_20200605_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='education_form',
            field=models.CharField(blank=True, choices=[('internal', 'Internal'), ('extramural', 'Extramural')], max_length=1024, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='qualification',
            field=models.CharField(blank=True, choices=[('primary_vocational_education', 'Primary vocational education'), ('secondary_vocational_education', 'Secondary vocational education'), ('bachelor', 'Bachelor'), ('specialist', 'Specialist'), ('master', 'Master')], max_length=1024, null=True, verbose_name='Квалификация'),
        ),
    ]
