# Generated by Django 2.2.6 on 2020-06-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0021_auto_20200605_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationtool',
            name='description',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='onlinecourse',
            name='description',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='Описание'),
        ),
    ]
