# Generated by Django 2.2.6 on 2020-06-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0022_auto_20200607_2204'),
        ('workprogramsapp', '0022_auto_20200607_2156'),
    ]

    operations = [
    ]
