# Generated by Django 2.2.6 on 2020-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0024_outcomesofworkprogram_evaluation_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='faculty',
            field=models.CharField(max_length=150, null=True, verbose_name='Факультет (Структурное подразделение)'),
        ),
    ]
