# Generated by Django 2.2.6 on 2020-06-12 16:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workprogramsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0025_fieldofstudy_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_profile', models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Профиль ОП')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementationAcademicPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), workprogramsapp.models.max_value_current_year])),
                ('academic_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.AcademicPlan', verbose_name='Учебный план')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.FieldOfStudy', verbose_name='Направление подготовки')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('implementation_academic_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.ImplementationAcademicPlan', verbose_name='Учебный план в направлении')),
                ('work_program', models.ManyToManyField(to='workprogramsapp.WorkProgram', verbose_name='Рабочая программа')),
            ],
        ),
        migrations.AddField(
            model_name='academicplan',
            name='field_of_study',
            field=models.ManyToManyField(through='workprogramsapp.ImplementationAcademicPlan', to='workprogramsapp.FieldOfStudy'),
        ),
    ]
