# Generated by Django 2.2.6 on 2020-06-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0026_auto_20200612_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicplan',
            name='approval_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='academicplan',
            name='number',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Номер учебного плана'),
        ),
        migrations.AlterField(
            model_name='academicplan',
            name='field_of_study',
            field=models.ManyToManyField(blank=True, null=True, through='workprogramsapp.ImplementationAcademicPlan', to='workprogramsapp.FieldOfStudy'),
        ),
    ]
