# Generated by Django 2.2.6 on 2020-06-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0026_auto_20200612_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicplan',
            name='field_of_study',
            field=models.ManyToManyField(blank=True, null=True, through='workprogramsapp.ImplementationAcademicPlan', to='workprogramsapp.FieldOfStudy'),
        ),
    ]
