# Generated by Django 2.2.6 on 2020-06-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0027_auto_20200612_1859'),
        ('workprogramsapp', '0027_auto_20200612_1753'),
    ]

    operations = [
    ]
