# Generated by Django 2.2.6 on 2020-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0027_auto_20200612_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplineblock',
            name='work_program',
            field=models.ManyToManyField(blank=True, null=True, to='workprogramsapp.WorkProgram', verbose_name='Рабочая программа'),
        ),
    ]
