# Generated by Django 2.2.6 on 2020-06-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0028_auto_20200614_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplineblock',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
