# Generated by Django 2.2.6 on 2020-06-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0029_auto_20200614_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplineblock',
            name='implementation_academic_plan',
        ),

    ]
