# Generated by Django 2.2.6 on 2020-06-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0030_auto_20200615_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplineblock',
            name='work_program',
        ),
        migrations.AlterField(
            model_name='disciplineblock',
            name='academic_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_blocks_in_academic_plan', to='workprogramsapp.AcademicPlan', verbose_name='Учебный план в направлении'),
        ),
        migrations.CreateModel(
            name='DisciplineBlockModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('descipline_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_in_discipline_block', to='workprogramsapp.DisciplineBlock', verbose_name='Модуль в блоке')),
                ('work_program', models.ManyToManyField(blank=True, null=True, to='workprogramsapp.WorkProgram', verbose_name='Рабочая программа')),
            ],
        ),
    ]
