# Generated by Django 2.2.6 on 2020-06-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0030_auto_20200615_1953'),
        ('workprogramsapp', '0028_merge_20200612_1908'),
    ]

    operations = [
    ]
