# Generated by Django 2.2.6 on 2020-06-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0031_auto_20200616_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplineblockmodule',
            name='work_program',
        ),
        migrations.CreateModel(
            name='WorkProgramChangeInDisciplineBlockModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_block_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_programs_in_modules', to='workprogramsapp.DisciplineBlockModule', verbose_name='Модуль в блоке')),
                ('work_program', models.ManyToManyField(blank=True, null=True, to='workprogramsapp.WorkProgram', verbose_name='Рабочая программа')),
            ],
        ),
    ]
