# Generated by Django 2.2.6 on 2020-06-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0031_merge_20200615_2009'),
        ('workprogramsapp', '0033_auto_20200616_1720'),
    ]

    operations = [
    ]
