# Generated by Django 2.2.6 on 2020-06-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0033_auto_20200616_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogramchangeindisciplineblockmodule',
            name='change_type',
            field=models.CharField(blank=True, choices=[('Required', 'Required'), ('Optionally', 'Optionally'), ('OGNP_set', 'OGNP_set'), ('Set_specialization', 'Set_specialization'), ('Facultativ', 'Facultativ')], max_length=1024, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='workprogramchangeindisciplineblockmodule',
            name='semester_hour',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
