# Generated by Django 2.2.6 on 2020-06-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0034_auto_20200619_0859'),
        ('workprogramsapp', '0034_merge_20200616_1728'),
    ]

    operations = [
    ]
