# Generated by Django 2.2.6 on 2020-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0035_auto_20200625_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogramchangeindisciplineblockmodule',
            name='code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
