# Generated by Django 2.2.6 on 2020-06-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0035_merge_20200620_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogram',
            name='approval_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workprogram',
            name='authors',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
