# Generated by Django 2.2.6 on 2020-06-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0035_merge_20200620_0946'),
    ]

    operations = [

    ]
