# Generated by Django 2.2.6 on 2020-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0036_auto_20200620_1736'),
    ]

    operations = [

    ]
