# Generated by Django 2.2.6 on 2020-06-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0036_workprogramchangeindisciplineblockmodule_code'),
        ('workprogramsapp', '0037_auto_20200624_1019'),
    ]

    operations = [
    ]
