# Generated by Django 2.2.6 on 2020-06-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0038_merge_20200625_1243'),
    ]

    operations = [

    ]
