# Generated by Django 2.2.6 on 2020-06-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0039_auto_20200625_1441'),
    ]
lineblock_academic_plan.py
 0040_disciplineblock_academic_plan.py
 0040_disciplineblock_academic_plan.py

