# Generated by Django 2.2.6 on 2020-06-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0039_auto_20200626_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomesofworkprogram',
            name='evaluation_tool',
            field=models.ManyToManyField(blank=True, null=True, related_name='evaluation_tool_of_outcomes', to='workprogramsapp.EvaluationTool', verbose_name='Оценочные средства'),
        ),
    ]
