# Generated by Django 2.2.6 on 2020-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0039_auto_20200625_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineblockmodule',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок модулей'),
        ),
        migrations.AlterModelOptions(
            name='disciplineblockmodule',
            options={'ordering': ['order']},
        ),

    ]
