# Generated by Django 2.2.6 on 2020-05-31 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0004_auto_20200531_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Повторения'),
        ),
        migrations.RemoveField(
            model_name='relation',
            name='item2',
        ),
        migrations.AddField(
            model_name='relation',
            name='item2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='dataprocessing.Items', verbose_name='Элемент РПД'),
        ),
    ]
