# Generated by Django 2.2.6 on 2020-06-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessing', '0005_auto_20200531_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={},
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
