export enum fields {
    COMPETENCE_LIST = 'COMPETENCE_LIST',
    COMPETENCE_DIALOG = 'COMPETENCE_DIALOG',
    IS_OPEN_DIALOG = 'IS_OPEN_DIALOG',
    DIALOG_DATA = 'DIALOG_DATA',
    SEARCH_QUERY = 'SEARCH_QUERY',
    CURRENT_PAGE = 'CURRENT_PAGE',
    ALL_COUNT = 'ALL_COUNT',
    SORTING = 'SORTING',
    SORTING_FIELD = 'SORTING_FIELD',
    SORTING_MODE = 'SORTING_MODE',
}

export enum fetchingTypes {
    GET_COMPETENCE = 'GET_COMPETENCE',
    DELETE_COMPETENCE = 'DELETE_COMPETENCE',
    UPDATE_COMPETENCE = 'UPDATE_COMPETENCE',
    CREATE_COMPETENCE = 'CREATE_COMPETENCE',
}

export enum CompetenceFields {
    ID = 'id',
    TITLE = 'title',
    NUMBER = 'number',
}