export enum fields {
  PROFESSIONS = 'PROFESSIONS',
  EDUCATIONAL_PROGRAMS = 'EDUCATIONAL_PROGRAMS',
  SELECTED_PROFESSIONS = 'SELECTED_PROFESSIONS',
  QUALIFICATION = 'QUALIFICATION',
  SELECTED_EDUCATIONAL_PROGRAMS = 'SELECTED_EDUCATIONAL_PROGRAMS',
}

export enum professionFields {
  ID = 'id',
  TITLE = 'title'
}

export enum fetchingTypes {
  GET_PROFESSIONS = 'GET_PROFESSIONS',
  GET_EDUCATIONAL_PROGRAMS = 'GET_EDUCATIONAL_PROGRAMS',
  SAVE_PROGRAMS = 'SAVE_PROGRAMS',
}

export enum selectListModes {
  SELECT = 'select',
  UNSELECT = 'unselect',
}
