export enum fields {
    TRAINING_ENTITIES_LIST = 'TRAINING_ENTITIES_LIST',
    TRAINING_ENTITIES_DIALOG = 'TRAINING_ENTITIES_DIALOG',
    IS_OPEN_DIALOG = 'IS_OPEN_DIALOG',
    DIALOG_DATA = 'DIALOG_DATA',
    SEARCH_QUERY = 'SEARCH_QUERY',
    CURRENT_PAGE = 'CURRENT_PAGE',
    ALL_COUNT = 'ALL_COUNT',
    SORTING = 'SORTING',
    SORTING_FIELD = 'SORTING_FIELD',
    SORTING_MODE = 'SORTING_MODE',
}

export enum fetchingTypes {
    GET_TRAINING_ENTITIES = 'GET_TRAINING_ENTITIES',
    DELETE_TRAINING_ENTITIES = 'DELETE_TRAINING_ENTITIES',
    UPDATE_TRAINING_ENTITIES = 'UPDATE_TRAINING_ENTITIES',
    CREATE_TRAINING_ENTITIES = 'CREATE_TRAINING_ENTITIES',
}

export enum TrainingEntitiesFields {
    ID = 'id',
    TITLE = 'name',
    SUBJECT_AREA = 'domain',
}