export enum fields {
    FETCHING = 'FETCHING',
    ERRORS = 'ERRORS',
    SUCCESS_MESSAGES = 'SUCCESS_MESSAGES',
    IS_AUTH = 'IS_AUTH',
    FETCHING_COMPONENT = 'FETCHING_COMPONENT',
    USERS = 'USERS',
    USER_DATA = 'USER_DATA',
    USER_GROUPS = 'USER_GROUPS',
    MOCK_MENU = 'MOCK_MENU',
    NOTIFICATIONS_COUNT = 'NOTIFICATIONS_COUNT',
    UNREAD_CHATS_COUNT = 'UNREAD_CHATS_COUNT',
    VALIDATION_RESULTS = 'VALIDATION_RESULTS',
    VALIDATION_RUN_RESULTS = 'VALIDATION_RUN_RESULTS',
}

export enum UserFields{
    FIRST_NAME = 'first_name',
    LAST_NAME = 'last_name',
    ID = 'id',
    USERNAME = 'username',
}
