export enum fields {
    SUBJECT_AREA_LIST = 'SUBJECT_AREA_LIST',
    SUBJECT_AREA_DIALOG = 'SUBJECT_AREA_DIALOG',
    IS_OPEN_DIALOG = 'IS_OPEN_DIALOG',
    DIALOG_DATA = 'DIALOG_DATA',
    SEARCH_QUERY = 'SEARCH_QUERY',
    CURRENT_PAGE = 'CURRENT_PAGE',
    ALL_COUNT = 'ALL_COUNT',
    SORTING = 'SORTING',
    SORTING_FIELD = 'SORTING_FIELD',
    SORTING_MODE = 'SORTING_MODE',
}

export enum fetchingTypes {
    GET_SUBJECT_AREA = 'GET_SUBJECT_AREA',
    DELETE_SUBJECT_AREA = 'DELETE_SUBJECT_AREA',
    UPDATE_SUBJECT_AREA = 'UPDATE_SUBJECT_AREA',
    CREATE_SUBJECT_AREA = 'CREATE_SUBJECT_AREA',
}

export enum SubjectAreaFields {
    ID = 'id',
    TITLE = 'name',
}